workspace = { members = ["cowsql-raft-sys"] }
[package]
name = "leather"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cowsql-raft-sys = { path = "cowsql-raft-sys" }
